"""Build an Arrangement from a hummed melody.

The melody itself is NEVER generated by the agent — it's the pitch-detected
notes from the user's hum, preserved verbatim. The agent's job is to pick
musical context (tempo, key, optional chord progression, optional drums) that
fits the melody.

Two layers:
  - `build_melody_only_arrangement`: pure, no LLM call. Used on first hum.
  - `agent_refine`: calls Claude Agent SDK to add/modify chords or drums based
    on a free-form intent ("add chords", "make it sadder", "add drums").
"""

from __future__ import annotations

import asyncio
import json
import logging
import re
from collections import Counter
from typing import Any

from claude_agent_sdk import (
    AssistantMessage,
    ClaudeAgentOptions,
    TextBlock,
    query,
)
from pydantic import ValidationError

from app.schemas import (
    Arrangement,
    Drums,
    Guitar,
    Key,
    Note,
)

log = logging.getLogger(__name__)

_PITCH_CLASSES = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"]

# Default BPM when the hum has no clear rhythm to estimate from.
_DEFAULT_BPM = 90

_AGENT_OPTIONS = ClaudeAgentOptions(
    system_prompt=(
        "You are Bubbles, an AI session musician. The user has hummed a melody "
        "and now wants accompaniment that supports THEIR melody. You DO NOT "
        "invent the melody — it stays exactly as hummed.\n\n"
        "Your job: pick tempo, key, optional chord progression, and optional "
        "drums based on the user's intent.\n\n"
        "Hard rules:\n"
        "- Reply with ONLY a JSON object. No markdown fences, no commentary.\n"
        "- Schema:\n"
        "  {\n"
        '    "tempo": int 60-180,\n'
        '    "key": {"tonic": "A"|"B"|"C"|"D"|"E"|"F"|"G"|sharps allowed,\n'
        '            "mode": "major"|"minor"|"dorian"|"mixolydian"},\n'
        '    "chord_progression": [4 chord symbols] OR [] for no chords,\n'
        '    "guitar": {"voicing": "open-strum"|"power"|"fingerpick"|"muted-chuck",\n'
        '               "rhythm": "<16-step DSL>",\n'
        '               "sample_set": "acoustic"|"electric-clean"|"electric-dirty"}\n'
        '              OR null when chord_progression is [],\n'
        '    "drums": {"kit": "rock"|"lofi",\n'
        '              "pattern": {"kick": "<16-step>",\n'
        '                          "snare": "<16-step>",\n'
        '                          "hat": "<16-step>"}}\n'
        '             OR null for no drums,\n'
        '    "rationale": "1-2 plain English sentences"\n'
        "  }\n\n"
        "16-step DSL: x=normal hit, X=accent, o=ghost, .=rest, -=sustain.\n"
        "Each pattern must be exactly 16 characters.\n\n"
        "Defaults when uncertain:\n"
        "- If the user says 'add chords' or 'with chords', return 4 chords + "
        "guitar; drums stays at its current value.\n"
        "- If the user says 'add drums', return drums; chord_progression "
        "stays at its current value.\n"
        "- If the user just hummed (no intent), return chord_progression=[] "
        "and drums=null — melody only.\n"
        "- For 'make it sadder' / 'heavier' / etc., adjust mode/tempo/chord "
        "choices; keep other layers as-is.\n"
        "Be conservative. Don't add layers the user didn't ask for."
    ),
    allowed_tools=[],
    max_turns=1,
    permission_mode="bypassPermissions",
)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def build_melody_only_arrangement(notes: list[Note], bpm: float | None = None) -> Arrangement:
    """First-press arrangement: just the hummed melody, no chords, no drums.

    Pure function. No LLM call. Sub-second response. This is what plays back
    immediately so the user hears their hum on the guitar before deciding
    whether to add chords or drums.
    """
    tonic_letter = _estimate_tonic(notes)
    tempo = _round_tempo(bpm or _DEFAULT_BPM)

    return Arrangement(
        tempo=tempo,
        key=Key(tonic=tonic_letter, mode="minor"),
        melody=notes,
        chord_progression=[],
        guitar=None,
        drums=None,
        rationale=(
            f"Your hum, played back in {tonic_letter} minor at {tempo} BPM. "
            "Tap + chords or + drums to add layers."
        ),
    )


async def agent_refine(
    notes: list[Note],
    intent: str,
    prior: Arrangement | None,
    bpm_hint: float | None = None,
) -> Arrangement:
    """Refine the arrangement using Claude. Melody is always preserved.

    The agent gets the prior arrangement (if any) and the user's intent. It
    returns updated tempo/key/chord_progression/guitar/drums. We splice in
    the original melody verbatim so it can never drift.
    """
    user_msg = _build_user_message(notes, intent, prior)

    for attempt in (1, 2):
        try:
            text = await _query_agent(user_msg)
            payload = _extract_json(text)
            # The agent never returns the melody — always overwrite with the
            # hum-derived notes, no matter what the model put there.
            payload["melody"] = [n.model_dump() for n in notes]
            arr = Arrangement.model_validate(payload)
            return arr
        except (ValidationError, json.JSONDecodeError) as exc:
            log.warning("Refine attempt %d failed: %s", attempt, exc)
            user_msg = (
                f"{user_msg}\n\nYour previous response did not match the schema. "
                "Reply with ONLY a JSON object matching it exactly."
            )
        except Exception as exc:  # noqa: BLE001
            log.warning("Refine attempt %d errored: %s", attempt, exc)
            break

    log.warning("Agent unavailable — returning prior arrangement with a note.")
    fallback = prior or build_melody_only_arrangement(notes, bpm_hint)
    fallback.rationale = (
        f"(Agent unavailable — kept prior arrangement.) Original: "
        f"{fallback.rationale}"
    )
    fallback.melody = notes
    return fallback


# ---------------------------------------------------------------------------
# Internals
# ---------------------------------------------------------------------------


async def _query_agent(prompt: str) -> str:
    chunks: list[str] = []
    async for message in query(prompt=prompt, options=_AGENT_OPTIONS):
        if isinstance(message, AssistantMessage):
            for block in message.content:
                if isinstance(block, TextBlock):
                    chunks.append(block.text)
    return "".join(chunks).strip()


def _build_user_message(
    notes: list[Note],
    intent: str,
    prior: Arrangement | None,
) -> str:
    parts: list[str] = [
        "User's hum (this is the melody — DO NOT change these notes):",
        _summarize_notes(notes),
    ]
    if prior is not None:
        # Strip the melody from the prior we show the model; it's noise.
        summary = prior.model_dump(exclude={"melody"})
        parts.append("\nCurrent arrangement (excluding melody):")
        parts.append(json.dumps(summary, indent=2))

    parts.append(f'\nUser intent: "{intent}"')
    parts.append(
        "\nReturn the updated arrangement as JSON. Do not include a melody "
        "field — the backend re-attaches the original hum notes."
    )
    return "\n".join(parts)


def _summarize_notes(notes: list[Note]) -> str:
    if not notes:
        return "(no clear notes detected)"
    lines = [
        f"  midi={n.midi} start={n.start:.2f}s end={n.end:.2f}s vel={n.velocity:.2f}"
        for n in notes[:48]
    ]
    if len(notes) > 48:
        lines.append(f"  ...and {len(notes) - 48} more notes")
    return "\n".join(lines)


_JSON_BLOCK_RE = re.compile(r"\{.*\}", re.DOTALL)


def _extract_json(text: str) -> dict[str, Any]:
    text = text.strip()
    if text.startswith("```"):
        text = text.strip("`")
        if text.lower().startswith("json"):
            text = text[4:].lstrip()
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        match = _JSON_BLOCK_RE.search(text)
        if not match:
            raise
        return json.loads(match.group(0))


def _estimate_tonic(notes: list[Note]) -> str:
    """Most-common pitch class wins. Default to A on silence."""
    if not notes:
        return "A"
    counts = Counter(n.midi % 12 for n in notes)
    idx, _ = counts.most_common(1)[0]
    return _PITCH_CLASSES[idx]


def _round_tempo(bpm: float) -> int:
    return max(60, min(180, int(round(bpm))))


# Sync wrappers for FastAPI route handlers that prefer not to manage the loop.
def agent_refine_sync(
    notes: list[Note],
    intent: str,
    prior: Arrangement | None,
    bpm_hint: float | None = None,
) -> Arrangement:
    return asyncio.run(agent_refine(notes, intent, prior, bpm_hint))
